apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  port: {{ .Values.configmap.data.port | quote }}
  MONGO_URI: {{ .Values.configmap.data.MONGO_URI | quote }}
  BACKEND_API: {{ .Values.configmap.data.BACKEND_API | quote }}
