apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database_service.name }}
  namespace: {{ .Values.database_statefulset.namespace }}
  labels:
    app: {{ .Values.database_service.name }}
spec:
  ports:
  - port: {{ .Values.database_service.ports.port }}
    name: {{ .Values.database_service.ports.name }}
  clusterIP: {{ .Values.database_service.clusterIP }}
  selector:
    app: {{ .Values.database_service.name }}
