apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.HPA.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.HPA.scaleTargetRef.name }}
  minReplicas: {{ .Values.HPA.min }}
  maxReplicas: {{ .Values.HPA.max }}
  metrics:
  - type: {{ .Values.HPA.metrics.type }}
    resource:
      name: {{ .Values.HPA.metrics.resource.name }}
      target:
        type: {{ .Values.HPA.metrics.resource.target.type }}
        averageUtilization: {{ .Values.HPA.metrics.resource.target.averageUtilization }}
