apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.first_name }}
spec:
  capacity:
    storage: {{ .Values.pv.capacity.storage}}
  volumeMode: {{ .Values.pv.volumeMode}}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.pv.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.storage.name}}
  awsElasticBlockStore:
    volumeID: {{ .Values.pv.awsElasticBlockStore.volumeID_1 }}
    fsType: {{ .Values.pv.awsElasticBlockStore.fsType}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.second_name }}
spec:
  capacity:
    storage: {{ .Values.pv.capacity.storage}}
  volumeMode: {{ .Values.pv.volumeMode}}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.pv.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.storage.name}}
  awsElasticBlockStore:
    volumeID: {{ .Values.pv.awsElasticBlockStore.volumeID_2 }}
    fsType: {{ .Values.pv.awsElasticBlockStore.fsType}}
