apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.name}}
  namespace: {{ .Values.storage.namespace }}
provisioner: {{ .Values.storage.provisioner}}
parameters:
  type: {{ .Values.storage.parameters.type }}
  fsType: {{ .Values.storage.parameters.fsType }}
